ALTER TYPE "GrowthEventType" ADD VALUE IF NOT EXISTS 'LISTING_FILTER_APPLY';
ALTER TYPE "GrowthEventType" ADD VALUE IF NOT EXISTS 'LISTING_VIEW_CHANGE';
ALTER TYPE "GrowthEventType" ADD VALUE IF NOT EXISTS 'LISTING_MAP_SELECT';
ALTER TYPE "GrowthEventType" ADD VALUE IF NOT EXISTS 'PREMODERATION_FLAGGED';
ALTER TYPE "GrowthEventType" ADD VALUE IF NOT EXISTS 'PREMODERATION_RELEASED';
ALTER TYPE "GrowthEventType" ADD VALUE IF NOT EXISTS 'PREMODERATION_CONFIRMED';
